### PR TITLE
docs(readme): add supported nodejs version

### PR DESCRIPTION
**Pull request by PCOffline**

### CODE REVIEW

**Comment by 4kimov** [comment]
Thanks for the suggestion. Instead of updating the README, could you add it to `engines.node` in `package.json`?

**Comment by PCOffline** [comment]
Perhaps both?

**Comment by 4kimov** [comment]
We generally don't support EOL platforms (unless there's demand for it), v18 is the oldest that still [has security support](https://endoflife.date/nodejs), so there shouldn't be surprises there; `package.json` will make it obvious.

**Comment by PCOffline** [comment]
@4kimov done, sry for the delay

**Comment by 4kimov** [comment]
Thank you.

**Pull request merged**
